#20260915_kpopmodder: Source-reviewed Java grammar golden rows, independent from parser implementation tables.
COMMAND_CASES = (
    ("attack", "좀비 세 마리 공격해 줘", "attack zombie 3", True),
    (
        "auto_deposit_trust",
        "여기를 자동 보관 장소로 등록해 줘",
        "auto_deposit_trust",
        False,
    ),
    (
        "auto_deposit_trusted_list",
        "자동 보관 장소 목록 보여 줘",
        "auto_deposit_trusted_list",
        False,
    ),
    (
        "auto_deposit_untrust",
        "자동 보관 장소 등록 해제해 줘",
        "auto_deposit_untrust",
        False,
    ),
    ("chatclef", "챗클레프 꺼 줘", "chatclef off", True),
    ("deposit", "철괴 16개 보관해 줘", "deposit iron_ingot 16", False),
    ("deposit_all", "인벤토리 전부 보관해 줘", "deposit_all", False),
    ("equip", "다이아몬드 흉갑 장착해 줘", "equip diamond_chestplate", False),
    ("find", "철 골렘 찾아 줘", "find entity minecraft:iron_golem approach", False),
    ("follow", "Alex 따라가 줘", "follow Alex", True),
    ("food", "음식 10포인트만큼 모아 줘", "food 10", False),
    ("gamer", "마인크래프트 엔딩까지 진행해 줘", "gamer", True),
    ("gamma", "밝기를 1.5로 설정해 줘", "gamma 1.5", False),
    ("get", "철괴 16개 구해 줘", "get iron_ingot 16", False),
    ("give", "Alex에게 철괴 세 개 줘", "give Alex iron_ingot 3", False),
    ("goto", "500, 90, -928 좌표로 가 줘", "goto 500 90 -928", False),
    ("hero", "적대 몹 계속 정리해 줘", "hero", True),
    ("idle", "가만히 있어 줘", "idle", True),
    ("locate_structure", "엔드 요새 찾아가 줘", "locate_structure stronghold", False),
    ("meat", "고기 10포인트만큼 모아 줘", "meat 10", False),
    ("overlay", "오버레이 꺼 줘", "overlay off", False),
    ("reload_settings", "마인크래프트 설정 다시 불러와 줘", "reload_settings", True),
    ("resetmemory", "챗클레프 대화 기록 초기화해 줘", "resetmemory", True),
    ("scan", "다이아몬드 원석 블록 위치 스캔해 줘", "scan DIAMOND_ORE", False),
    ("stop", "멈춰 줘", "stop", False),
    ("store_home", "아이템 집에 정리해 줘", "store_home", False),
)

OPTION_CASES = (
    ("좀비 공격해 줘", "attack zombie 1", True),
    ("자동 보관 장소 test-id 등록 해제해 줘", "auto_deposit_untrust test-id", False),
    ("주변 16x16 자동 보관 장소 등록해 줘", "auto_deposit_trust area 16x16", False),
    ("장비와 도구를 제외한 아이템 전부 보관해 줘", "deposit", False),
    (
        "철괴 두 개와 금괴 세 개 보관해 줘",
        "deposit [iron_ingot 2, gold_ingot 3]",
        False,
    ),
    (
        "철괴 두 개와 금괴 세 개 전체 보관해 줘",
        "deposit_all [iron_ingot 2, gold_ingot 3]",
        False,
    ),
    ("철괴 두 개와 금괴 세 개 구해 줘", "get [iron_ingot 2, gold_ingot 3]", False),
    ("철괴 두 개와 철괴 세 개 구해 줘", "get [iron_ingot 5]", False),
    ("철괴 구해 줘", "get iron_ingot 1", False),
    ("철 방어구 세트 장착해 줘", "equip iron", False),
    (
        "철 흉갑 하나와 철 신발 하나 장착해 줘",
        "equip [iron_chestplate 1, iron_boots 1]",
        False,
    ),
    ("나에게 철괴 두 개 줘", "give iron_ingot 2", False),
    ("나 따라와 줘", "follow", True),
    ("스캔해 줘", "scan", False),
    ("밝기를 기본값으로 돌려 줘", "gamma 1.0", False),
    ("철 골렘 위치만 알려 줘", "find entity minecraft:iron_golem report", False),
    ("오버레이 켜 줘", "overlay on", False),
    ("챗클레프 켜 줘", "chatclef on", True),
    ("사막 사원 찾아가 줘", "locate_structure desert_temple", False),
    ("X 500 Z -928 좌표로 가 줘", "goto 500 -928", False),
    ("높이 90으로 가 줘", "goto 90", False),
    ("네더로 가 줘", "goto nether", False),
    ("500 90 -928 네더로 가 줘", "goto 500 90 -928 nether", False),
    ("자동보관등록 영역 16x16", "auto_deposit_trust area 16x16", False),
)
