#20260905_kpopmodder: Define the immutable canonical STOP transition schema.
STOP_CONTROL_TRANSITION_WIRE_DATA_FIELDS = (
    "java_socket_generation",
    "target_scope",
    "target_resolution",
    "requested_target_request_id",
    "requested_target_command_message_id",
    "requested_target_session_id",
    "requested_target_server_connection_generation",
    "resolved_target_request_id",
    "resolved_target_command_message_id",
    "resolved_target_session_id",
    "resolved_target_server_connection_generation",
    "control_outcome",
    "target_state_before",
    "target_state_after",
    "control_reason",
    "executed_client_tick",
    "verified_client_tick",
    "stop_command_invoked",
    "original_result_delivery",
)

STOP_CONTROL_TRANSITION_CANONICAL_FIELDS = (
    "control_request_id",
    "control_message_id",
    "session_id",
    "server_connection_generation",
    "accepted_session_id_at_validation",
    "accepted_server_connection_generation_at_validation",
    "java_socket_generation",
    "target_scope",
    "target_resolution",
    "requested_target_request_id",
    "requested_target_command_message_id",
    "requested_target_session_id",
    "requested_target_server_connection_generation",
    "invalid_target_fields_mask",
    "resolved_target_request_id",
    "resolved_target_command_message_id",
    "resolved_target_session_id",
    "resolved_target_server_connection_generation",
    "control_status",
    "control_outcome",
    "target_state_before",
    "target_state_after",
    "control_reason",
    "diagnostic_disposition",
    "executed_client_tick",
    "verified_client_tick",
    "stop_command_invoked",
    "original_result_delivery",
    "control_result_delivery",
    "python_stop_barrier_state",
    "java_stop_barrier_state",
    "ordinary_owner_gate_state",
    "frozen_python_owner_exact_match",
    "quarantine_active",
    "retirement_evidence_kind",
)


__all__ = (
    "STOP_CONTROL_TRANSITION_CANONICAL_FIELDS",
    "STOP_CONTROL_TRANSITION_WIRE_DATA_FIELDS",
)
