package lavi.minecraft.diagnostics.container.store.deposit.terminal.accounting;

//20260831_kpopmodder: Keep terminal-ledger saturation evidence in one fixed, bounded domain.
public enum StoreDepositTerminalSaturationFlag {
    TOTAL_TERMINAL_OBSERVED,
    TERMINAL_SEQUENCE,
    ADMISSION_PENDING,
    ADMISSION_GRANTED,
    SUPPRESSED_BEFORE_ADMISSION,
    EMISSION_PENDING,
    EMISSION_COMPLETED,
    EMISSION_FAILED_AFTER_ADMISSION,
    DUPLICATE_FINALIZATION_ATTEMPTS,
    TERMINAL_CONTEXT_AVAILABLE,
    TERMINAL_CONTEXT_UNAVAILABLE,
    TERMINAL_BOUNDARY_WITHOUT_CONTEXT,
    PARTIAL_MODE_DISABLED_COVERAGE_GAP,
    MODE_DISABLED_INVALIDATED_CONTEXT,
    LEDGER_COVERAGE_GAP,
    LEDGER_REVISION,
    OMITTED_ABNORMAL_SAMPLE,
    CLASSIFICATION_COUNT,
    SCOPE_COUNT,
    ACTIVE_TOKEN_REGISTRY_OVERFLOW,
    SNAPSHOT_SEQUENCE,
    RECONCILIATION_SUM
}
