#20260717_kpopmodder: Isolates the StarCraft116 bridge protocol from its adapter implementation.
from typing import Any, Dict, Optional, Protocol


class StarCraft116BridgeProtocol(Protocol):
    #20260706_kpopmodder: Keep the protocol explicit while adapter code stays concrete and small.
    def start_status_listener(self, callback=None): ...
    def stop_status_listener(self): ...
    def start_game(self, profile_name: Optional[str] = None): ...
    def stop_game(self): ...
    def send_command(self, command: Any) -> Dict[str, Any]: ...
    def get_status(self) -> Dict[str, Any]: ...
    def poll_once(self) -> int: ...
