#20260717_kpopmodder: Isolates the StarCraft116 worker protocol from its implementation.
from typing import Any, Dict, Protocol


class StarCraft116WorkerProtocol(Protocol):
    #20260706_kpopmodder: Define minimal worker protocol for queue/loop ownership.
    def start(self) -> bool: ...
    def stop(self) -> bool: ...
    def submit(self, command: Any) -> bool: ...
    def handle_command(self, command: Any) -> Dict[str, Any]: ...
    def get_status(self) -> Dict[str, Any]: ...
