#20260705_kpopmodder: Keep optional direct plugin metadata out of app composition code.
OPTIONAL_MODULE_MANIFEST = {
    "SongPlayer": {
        "id": "SongPlayer",
        "display_name": "Song Player",
        "api_version": "1",
        "module_path": "plugins.SongPlayer.SongPlayer",
        "class_name": "SongPlayer",
        "default_enabled": True,
        "dependency_group": "Full",
        "capabilities": ("song_playback", "vtuber_expression"),
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "Chess": {
        "id": "Chess",
        "display_name": "Chess",
        "api_version": "1",
        "module_path": "plugins.Chess.Chess",
        "class_name": "Chess",
        "default_enabled": False,
        "dependency_group": "Full",
        "capabilities": ("game_extension", "chess"),
        "required_python_packages": ("chess",),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "StarCraftRemastered": {
        "id": "StarCraftRemastered",
        "display_name": "StarCraft Remastered",
        "api_version": "1",
        "module_path": "plugins.StarCraftRemastered.starcraft_remastered",
        "class_name": "StarCraftRemastered",
        "default_enabled": False,
        "dependency_group": "Full",
        "capabilities": ("game_extension", "starcraft_remastered"),
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "StarCraft116": {
        "id": "StarCraft116",
        "display_name": "StarCraft 1.16",
        "api_version": "1",
        "module_path": "plugins.StarCraft116.starcraft116",
        "class_name": "StarCraft116",
        "default_enabled": False,
        "dependency_group": "Full",
        "capabilities": ("game_extension", "starcraft116"),
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "StarCraft2": {
        "id": "StarCraft2",
        "display_name": "StarCraft2",
        "api_version": "1",
        "module_path": "plugins.StarCraft2.starcraft2",
        "class_name": "StarCraft2",
        "default_enabled": False,
        "dependency_group": "Full",
        "capabilities": ("game_extension", "starcraft2"),
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "ScreenVision": {
        "id": "ScreenVision",
        "display_name": "Screen Vision",
        "api_version": "1",
        "module_path": "plugins.ScreenVision.screenVision",
        "class_name": "ScreenVision",
        "default_enabled": True,
        "dependency_group": "Full",
        "capabilities": ("screen_observation", "vision_context"),
        "required_python_packages": ("PIL", "torch", "transformers"),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": False,
        "supports_cpu": False,
        "requires_gpu": True,
    },
}


def get_optional_module_manifest(module_name):
    return OPTIONAL_MODULE_MANIFEST[module_name]
