#20260705_kpopmodder: Keep optional direct plugin metadata out of app composition code.
OPTIONAL_MODULE_MANIFEST = {
    "SongPlayer": {
        "id": "SongPlayer",
        "display_name": "Song Player",
        "api_version": "1",
        "module_path": "plugins.SongPlayer.SongPlayer",
        "class_name": "SongPlayer",
        "default_enabled": True,
        "dependency_group": "Full",
        "capabilities": ("song_playback", "vtuber_expression"),
        "config_schema": {
            "SongPlayer": {
                "manifest_path": "plugins/SongPlayer/config/song_player_songs.json",
            },
        },
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "Chess": {
        "id": "Chess",
        "display_name": "Chess",
        "api_version": "1",
        "module_path": "plugins.Chess.Chess",
        "class_name": "Chess",
        "default_enabled": False,
        "dependency_group": "Games",
        "capabilities": ("game_extension", "chess"),
        "config_schema": {
            "Chess": {
                "config_path": "plugins/Chess/config/chess_config.json",
                "lc0_path": "",
                "weights_path": "",
                "web_server_port": 8790,
            },
        },
        "required_python_packages": ("chess",),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "StarCraftRemastered": {
        "id": "StarCraftRemastered",
        "display_name": "StarCraft Remastered",
        "api_version": "1",
        "module_path": "plugins.StarCraftRemastered.starcraft_remastered",
        "class_name": "StarCraftRemastered",
        "default_enabled": False,
        "dependency_group": "Games",
        "capabilities": ("game_extension", "starcraft_remastered"),
        "config_schema": {
            "StarCraftRemastered": {
                "enabled": False,
            },
        },
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "StarCraft116": {
        "id": "StarCraft116",
        "display_name": "StarCraft 1.16",
        "api_version": "1",
        "module_path": "plugins.StarCraft116.starcraft116",
        "class_name": "StarCraft116",
        "default_enabled": False,
        "dependency_group": "Games",
        "capabilities": ("game_extension", "starcraft116"),
        "config_schema": {
            "StarCraft116": {
                "config_path": "plugins/StarCraft116/config/starcraft116_config.json",
                "enabled": False,
                "active_profile": "saida",
            },
        },
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "StarCraft2": {
        "id": "StarCraft2",
        "display_name": "StarCraft2",
        "api_version": "1",
        "module_path": "plugins.StarCraft2.starcraft2",
        "class_name": "StarCraft2",
        "default_enabled": False,
        "dependency_group": "Games",
        "capabilities": ("game_extension", "starcraft2"),
        "config_schema": {
            "StarCraft2": {
                "config_path": "plugins/StarCraft2/config/starcraft2_config.json",
                "enabled": False,
                "race": "Protoss",
            },
        },
        "required_python_packages": (),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": True,
        "supports_cpu": True,
    },
    "ScreenVision": {
        "id": "ScreenVision",
        "display_name": "Screen Vision",
        "api_version": "1",
        "module_path": "plugins.ScreenVision.screenVision",
        "class_name": "ScreenVision",
        "default_enabled": True,
        "dependency_group": "Vision",
        "capabilities": ("screen_observation", "vision_context"),
        "config_schema": {
            "ScreenVision": {
                "model": "Qwen/Qwen2.5-VL-3B-Instruct",
                "device": "auto",
                "auto_watch_enabled": True,
            },
        },
        "required_python_packages": ("PIL", "torch", "transformers"),
        "required_files": (),
        "required_executables": (),
        "required_services": (),
        "supports_offline": False,
        "supports_cpu": False,
        "requires_gpu": True,
    },
}


def get_optional_module_manifest(module_name):
    return OPTIONAL_MODULE_MANIFEST[module_name]
