#20260717_kpopmodder: Isolates the StarCraft2 worker protocol from its implementation.
from typing import Any, Dict, Protocol


class StarCraft2WorkerProtocol(Protocol):
    #20260707_kpopmodder: Minimal async worker API for StarCraft2 command routing.
    def start(self) -> bool: ...
    def stop(self) -> bool: ...
    def submit(self, command: Any) -> bool: ...
    def handle_command(self, command: Any) -> Dict[str, Any]: ...
    def get_status(self) -> Dict[str, Any]: ...
