#20260717_kpopmodder: Isolates the StarCraft2 bridge protocol from its adapter implementation.
from typing import Any, Dict, Optional, Protocol


class StarCraft2BridgeProtocol(Protocol):
    #20260707_kpopmodder: Narrow command bridge for StarCraft2 worker and extension callers.
    def send_command(self, command: Any) -> Dict[str, Any]: ...
    def start_game(self, overrides: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def stop_game(self) -> Dict[str, Any]: ...
    def get_status(self) -> Dict[str, Any]: ...
