#20260905_kpopmodder: Lock flattened ChatClef Python responsibility packages.
from __future__ import annotations

import ast
from importlib import import_module
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
FLATTENED_MODULES = (
    (
        "plugins/Minecraft/fabric/chatclef/command_registry/admission/korean_command/auto_deposit_trust/admission",
        "plugins/Minecraft/fabric/chatclef/command_registry/admission/korean_command/auto_deposit_trust/korean_auto_deposit_trust_inspector.py",
        "plugins.Minecraft.fabric.chatclef.command_registry.admission.korean_command.auto_deposit_trust.korean_auto_deposit_trust_inspector",
        "KoreanAutoDepositTrustInspector",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/command_registry/admission/korean_command/auto_deposit_trust/lifecycle",
        "plugins/Minecraft/fabric/chatclef/command_registry/admission/korean_command/auto_deposit_trust/korean_auto_deposit_trust_claim_lifecycle.py",
        "plugins.Minecraft.fabric.chatclef.command_registry.admission.korean_command.auto_deposit_trust.korean_auto_deposit_trust_claim_lifecycle",
        "KoreanAutoDepositTrustClaimLifecycle",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/generic_crafting_defaults/submission/composition",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/generic_crafting_defaults/submission/generic_crafting_submission_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.generic_crafting_defaults.submission.generic_crafting_submission_component_graph",
        "GenericCraftingSubmissionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/generic_crafting_defaults/translation/composition",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/generic_crafting_defaults/translation/generic_crafting_translation_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.generic_crafting_defaults.translation.generic_crafting_translation_component_graph",
        "GenericCraftingTranslationComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/composition",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/translated_command_pipeline_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.pipeline.translated_command_pipeline_component_graph",
        "TranslatedCommandPipelineComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/failure",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/translated_command_submission_failure_handler.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.pipeline.translated_command_submission_failure_handler",
        "TranslatedCommandSubmissionFailureHandler",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/guard",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/translated_command_pre_submit_guard.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.pipeline.translated_command_pre_submit_guard",
        "TranslatedCommandPreSubmitGuard",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/request",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/translated_command_pipeline_request_builder.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.pipeline.translated_command_pipeline_request_builder",
        "TranslatedCommandPipelineRequestBuilder",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/result",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/translated_command_submission_result_handler.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.pipeline.translated_command_submission_result_handler",
        "TranslatedCommandSubmissionResultHandler",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/transport",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/pipeline/translated_command_transport_invoker.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.pipeline.translated_command_transport_invoker",
        "TranslatedCommandTransportInvoker",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/stages/admission/composition",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/stages/admission/translated_command_admission_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.stages.admission.translated_command_admission_component_graph",
        "TranslatedCommandAdmissionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/stages/dto",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/stages/translated_command_dto_policy.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.stages.translated_command_dto_policy",
        "TranslatedCommandDtoPolicy",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/stages/input",
        "plugins/Minecraft/fabric/chatclef/extension/natural_language/submission/stages/translated_command_input_reader.py",
        "plugins.Minecraft.fabric.chatclef.extension.natural_language.submission.stages.translated_command_input_reader",
        "TranslatedCommandInputReader",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/aliases/generic_crafting_defaults/activation/binding_validation/composition",
        "plugins/Minecraft/fabric/chatclef/input/aliases/generic_crafting_defaults/activation/binding_validation/generic_crafting_activation_binding_validation_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.aliases.generic_crafting_defaults.activation.binding_validation.generic_crafting_activation_binding_validation_component_graph",
        "GenericCraftingActivationBindingValidationComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/aliases/generic_crafting_defaults/routing/failure",
        "plugins/Minecraft/fabric/chatclef/input/aliases/generic_crafting_defaults/routing/generic_crafting_route_failure_handler.py",
        "plugins.Minecraft.fabric.chatclef.input.aliases.generic_crafting_defaults.routing.generic_crafting_route_failure_handler",
        "GenericCraftingRouteFailureHandler",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/auto_deposit_trust/routing/lifecycle",
        "plugins/Minecraft/fabric/chatclef/input/auto_deposit_trust/routing/auto_deposit_trust_route_execution_lifecycle.py",
        "plugins.Minecraft.fabric.chatclef.input.auto_deposit_trust.routing.auto_deposit_trust_route_execution_lifecycle",
        "AutoDepositTrustRouteExecutionLifecycle",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/auto_deposit_trust/routing/orchestration",
        "plugins/Minecraft/fabric/chatclef/input/auto_deposit_trust/routing/auto_deposit_trust_route_sequence.py",
        "plugins.Minecraft.fabric.chatclef.input.auto_deposit_trust.routing.auto_deposit_trust_route_sequence",
        "AutoDepositTrustRouteSequence",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/ownership/item_command/composition",
        "plugins/Minecraft/fabric/chatclef/input/ownership/item_command/item_command_ownership_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.ownership.item_command.item_command_ownership_component_graph",
        "ItemCommandOwnershipComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/ownership/item_command/generic_crafting",
        "plugins/Minecraft/fabric/chatclef/input/ownership/item_command/generic_crafting_candidate_ownership_classifier.py",
        "plugins.Minecraft.fabric.chatclef.input.ownership.item_command.generic_crafting_candidate_ownership_classifier",
        "GenericCraftingCandidateOwnershipClassifier",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/minecraft_route_decision_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.decisions.minecraft_route_decision_component_graph",
        "MinecraftRouteDecisionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/minecraft_submission_route_decision_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.decisions.submission.minecraft_submission_route_decision_component_graph",
        "MinecraftSubmissionRouteDecisionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/precheck",
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/minecraft_precheck_route_decision_factory.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.decisions.submission.minecraft_precheck_route_decision_factory",
        "MinecraftPrecheckRouteDecisionFactory",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/reconciliation",
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/minecraft_reconciled_route_decision_factory.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.decisions.submission.minecraft_reconciled_route_decision_factory",
        "MinecraftReconciledRouteDecisionFactory",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/submitted",
        "plugins/Minecraft/fabric/chatclef/input/routing/decisions/submission/minecraft_submitted_route_decision_factory.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.decisions.submission.minecraft_submitted_route_decision_factory",
        "MinecraftSubmittedRouteDecisionFactory",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/cleanup",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/minecraft_generic_crafting_dispatch_cleanup.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.minecraft_generic_crafting_dispatch_cleanup",
        "MinecraftGenericCraftingDispatchCleanup",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/minecraft_input_route_ordering_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.minecraft_input_route_ordering_component_graph",
        "MinecraftInputRouteOrderingComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/gating",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/minecraft_input_gate_inspector.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.minecraft_input_gate_inspector",
        "MinecraftInputGateInspector",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/invocation/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/invocation/minecraft_optional_route_owner_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.invocation.minecraft_optional_route_owner_component_graph",
        "MinecraftOptionalRouteOwnerComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/invocation/execution",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/invocation/minecraft_optional_route_owner_call.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.invocation.minecraft_optional_route_owner_call",
        "MinecraftOptionalRouteOwnerCall",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/invocation/failure",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/invocation/minecraft_optional_route_owner_failure_converter.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.invocation.minecraft_optional_route_owner_failure_converter",
        "MinecraftOptionalRouteOwnerFailureConverter",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/ordering",
        "plugins/Minecraft/fabric/chatclef/input/routing/orchestration/minecraft_input_route_sequence.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.orchestration.minecraft_input_route_sequence",
        "MinecraftInputRouteSequence",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/availability",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/ordinary_route_availability_stage.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.ordinary_route_availability_stage",
        "OrdinaryRouteAvailabilityStage",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/orchestration",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/ordinary_minecraft_command_route_pipeline.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.ordinary_minecraft_command_route_pipeline",
        "OrdinaryMinecraftCommandRoutePipeline",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/precheck/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/precheck/ordinary_submission_precheck_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.precheck.ordinary_submission_precheck_component_graph",
        "OrdinarySubmissionPrecheckComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/precheck/diagnostics",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/precheck/ordinary_submission_precheck_diagnostics.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.precheck.ordinary_submission_precheck_diagnostics",
        "OrdinarySubmissionPrecheckDiagnostics",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/precheck/evaluation",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/precheck/ordinary_submission_precheck_evaluator.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.precheck.ordinary_submission_precheck_evaluator",
        "OrdinarySubmissionPrecheckEvaluator",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/reconciliation",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/ordinary_submission_reconciliation_stage.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.ordinary_submission_reconciliation_stage",
        "OrdinarySubmissionReconciliationStage",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/rejection/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/rejection/ordinary_translation_rejection_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.rejection.ordinary_translation_rejection_component_graph",
        "OrdinaryTranslationRejectionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/rejection/item",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/rejection/ordinary_item_translation_rejection_owner.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.rejection.ordinary_item_translation_rejection_owner",
        "OrdinaryItemTranslationRejectionOwner",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/rejection/status",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/rejection/ordinary_generic_translation_rejection.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.rejection.ordinary_generic_translation_rejection",
        "OrdinaryGenericTranslationRejection",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/ordinary_submission_result_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.submission.ordinary_submission_result_component_graph",
        "OrdinarySubmissionResultComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/decision",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/ordinary_submission_decision_builder.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.submission.ordinary_submission_decision_builder",
        "OrdinarySubmissionDecisionBuilder",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/diagnostics",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/ordinary_submission_result_diagnostics.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.submission.ordinary_submission_result_diagnostics",
        "OrdinarySubmissionResultDiagnostics",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/reconciliation",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/ordinary_submission_result_reconciler.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.submission.ordinary_submission_result_reconciler",
        "OrdinarySubmissionResultReconciler",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/transport",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/submission/ordinary_submission_transport.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.submission.ordinary_submission_transport",
        "OrdinarySubmissionTransport",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/translation/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/translation/ordinary_translation_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.translation.ordinary_translation_component_graph",
        "OrdinaryTranslationComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/translation/invocation",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/translation/ordinary_translation_invocation.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.translation.ordinary_translation_invocation",
        "OrdinaryTranslationInvocation",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/translation/validation",
        "plugins/Minecraft/fabric/chatclef/input/routing/ordinary/translation/ordinary_translation_dto_validation.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.ordinary.translation.ordinary_translation_dto_validation",
        "OrdinaryTranslationDtoValidation",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/minecraft_chatclef_submission_boundary_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.submission.minecraft_chatclef_submission_boundary_component_graph",
        "MinecraftChatClefSubmissionBoundaryComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/outcome",
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/minecraft_chatclef_submission_outcome_validator.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.submission.minecraft_chatclef_submission_outcome_validator",
        "MinecraftChatClefSubmissionOutcomeValidator",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/request",
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/minecraft_chatclef_submission_request_builder.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.submission.minecraft_chatclef_submission_request_builder",
        "MinecraftChatClefSubmissionRequestBuilder",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/transport",
        "plugins/Minecraft/fabric/chatclef/input/routing/submission/minecraft_chatclef_submission_transport_invoker.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.submission.minecraft_chatclef_submission_transport_invoker",
        "MinecraftChatClefSubmissionTransportInvoker",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/capability",
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/minecraft_chatclef_translation_capability_inspector.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.translation.minecraft_chatclef_translation_capability_inspector",
        "MinecraftChatClefTranslationCapabilityInspector",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/minecraft_chatclef_translation_boundary_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.translation.minecraft_chatclef_translation_boundary_component_graph",
        "MinecraftChatClefTranslationBoundaryComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/invocation",
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/minecraft_chatclef_translation_invoker.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.translation.minecraft_chatclef_translation_invoker",
        "MinecraftChatClefTranslationInvoker",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/result",
        "plugins/Minecraft/fabric/chatclef/input/routing/translation/minecraft_chatclef_translation_result_validator.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.translation.minecraft_chatclef_translation_result_validator",
        "MinecraftChatClefTranslationResultValidator",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/composition",
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/trusted_korean_input_route_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.trusted_korean.trusted_korean_input_route_component_graph",
        "TrustedKoreanInputRouteComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/diagnostics",
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/trusted_korean_feature_admission_observer.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.trusted_korean.trusted_korean_feature_admission_observer",
        "TrustedKoreanFeatureAdmissionObserver",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/lifecycle",
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/trusted_korean_proof_lifecycle_closer.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.trusted_korean.trusted_korean_proof_lifecycle_closer",
        "TrustedKoreanProofLifecycleCloser",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/routing",
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/trusted_korean_route_invoker.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.trusted_korean.trusted_korean_route_invoker",
        "TrustedKoreanRouteInvoker",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/validation",
        "plugins/Minecraft/fabric/chatclef/input/routing/trusted_korean/trusted_korean_proof_validator.py",
        "plugins.Minecraft.fabric.chatclef.input.routing.trusted_korean.trusted_korean_proof_validator",
        "TrustedKoreanProofValidator",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/stop/claims/store",
        "plugins/Minecraft/fabric/chatclef/input/stop/claims/stop_control_claim_record_store.py",
        "plugins.Minecraft.fabric.chatclef.input.stop.claims.stop_control_claim_record_store",
        "StopControlClaimRecordStore",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/input/stop/routing/classification",
        "plugins/Minecraft/fabric/chatclef/input/stop/routing/stop_input_decision_observer.py",
        "plugins.Minecraft.fabric.chatclef.input.stop.routing.stop_input_decision_observer",
        "StopInputDecisionObserver",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/response/generic_crafting_defaults",
        "plugins/Minecraft/fabric/chatclef/response/generic_crafting_defaults_response_renderer.py",
        "plugins.Minecraft.fabric.chatclef.response.generic_crafting_defaults_response_renderer",
        "GenericCraftingDefaultsResponseRenderer",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/response/trusted_korean/selection",
        "plugins/Minecraft/fabric/chatclef/response/trusted_korean/trusted_korean_feedback_route_selector.py",
        "plugins.Minecraft.fabric.chatclef.response.trusted_korean.trusted_korean_feedback_route_selector",
        "TrustedKoreanFeedbackRouteSelector",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/composition",
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/fabric_chatclef_command_submission_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.transport.command_submission.fabric_chatclef_command_submission_component_graph",
        "FabricChatClefCommandSubmissionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/envelope",
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/fabric_chatclef_command_envelope_factory.py",
        "plugins.Minecraft.fabric.chatclef.transport.command_submission.fabric_chatclef_command_envelope_factory",
        "FabricChatClefCommandEnvelopeFactory",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/orchestration",
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/fabric_chatclef_command_submission_sequence.py",
        "plugins.Minecraft.fabric.chatclef.transport.command_submission.fabric_chatclef_command_submission_sequence",
        "FabricChatClefCommandSubmissionSequence",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/outcome",
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/fabric_chatclef_command_delivery_outcome_policy.py",
        "plugins.Minecraft.fabric.chatclef.transport.command_submission.fabric_chatclef_command_delivery_outcome_policy",
        "FabricChatClefCommandDeliveryOutcomePolicy",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/results",
        "plugins/Minecraft/fabric/chatclef/transport/command_submission/fabric_chatclef_command_result_factory.py",
        "plugins.Minecraft.fabric.chatclef.transport.command_submission.fabric_chatclef_command_result_factory",
        "FabricChatClefCommandResultFactory",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/result_handling/composition",
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/result_handling/stop_control_result_handling_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.transport.control.stop.result_handling.stop_control_result_handling_component_graph",
        "StopControlResultHandlingComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/result_handling/parsing",
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/result_handling/stop_control_result_parser.py",
        "plugins.Minecraft.fabric.chatclef.transport.control.stop.result_handling.stop_control_result_parser",
        "StopControlResultParser",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/composition",
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/stop_control_submission_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.transport.control.stop.submission.stop_control_submission_component_graph",
        "StopControlSubmissionComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/prewrite/diagnostics",
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/prewrite/stop_control_prewrite_diagnostic_reporter.py",
        "plugins.Minecraft.fabric.chatclef.transport.control.stop.submission.prewrite.stop_control_prewrite_diagnostic_reporter",
        "StopControlPrewriteDiagnosticReporter",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/prewrite/outcome",
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/prewrite/stop_control_prewrite_result_policy.py",
        "plugins.Minecraft.fabric.chatclef.transport.control.stop.submission.prewrite.stop_control_prewrite_result_policy",
        "StopControlPrewriteResultPolicy",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/send_outcome/composition",
        "plugins/Minecraft/fabric/chatclef/transport/control/stop/submission/send_outcome/stop_control_send_outcome_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.transport.control.stop.submission.send_outcome.stop_control_send_outcome_component_graph",
        "StopControlSendOutcomeComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/acknowledgement",
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/fabric_chatclef_handshake_acknowledger.py",
        "plugins.Minecraft.fabric.chatclef.transport.server.client_session.handshake.fabric_chatclef_handshake_acknowledger",
        "FabricChatClefHandshakeAcknowledger",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/admission",
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/fabric_chatclef_handshake_admission.py",
        "plugins.Minecraft.fabric.chatclef.transport.server.client_session.handshake.fabric_chatclef_handshake_admission",
        "FabricChatClefHandshakeAdmission",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/composition",
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/fabric_chatclef_handshake_component_graph.py",
        "plugins.Minecraft.fabric.chatclef.transport.server.client_session.handshake.fabric_chatclef_handshake_component_graph",
        "FabricChatClefHandshakeComponentGraph",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/diagnostics",
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/fabric_chatclef_handshake_diagnostics.py",
        "plugins.Minecraft.fabric.chatclef.transport.server.client_session.handshake.fabric_chatclef_handshake_diagnostics",
        "FabricChatClefHandshakeDiagnostics",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/identity",
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/fabric_chatclef_session_id_factory.py",
        "plugins.Minecraft.fabric.chatclef.transport.server.client_session.handshake.fabric_chatclef_session_id_factory",
        "FabricChatClefSessionIdFactory",
    ),
    (
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/persistence",
        "plugins/Minecraft/fabric/chatclef/transport/server/client_session/handshake/fabric_chatclef_handshake_session_persistence.py",
        "plugins.Minecraft.fabric.chatclef.transport.server.client_session.handshake.fabric_chatclef_handshake_session_persistence",
        "FabricChatClefHandshakeSessionPersistence",
    ),
)


def test_obsolete_single_file_leaf_packages_are_absent() -> None:
    for old_package, target_path, _, _ in FLATTENED_MODULES:
        old_directory = REPOSITORY_ROOT / old_package
        assert not tuple(old_directory.glob("*.py")), old_package
        assert (REPOSITORY_ROOT / target_path).is_file(), target_path


def test_flattened_modules_and_parent_exports_are_importable() -> None:
    for _, _, module_name, class_name in FLATTENED_MODULES:
        module = import_module(module_name)
        exported_type = getattr(module, class_name)
        parent_package = import_module(module_name.rsplit(".", 1)[0])
        assert getattr(parent_package, class_name) is exported_type


def test_flattened_modules_keep_one_marked_class_per_file() -> None:
    for _, target_path, _, class_name in FLATTENED_MODULES:
        path = REPOSITORY_ROOT / target_path
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
        class_names = tuple(
            node.name for node in tree.body if isinstance(node, ast.ClassDef)
        )
        assert class_names == (class_name,), target_path
        assert "20260905_kpopmodder" in "\n".join(source.splitlines()[:5])
