package lavi.minecraft.diagnostics.crafting.acquisition.terminal;

//20260901_kpopmodder: Expose one immutable terminal aggregate without reevaluating gameplay.
public record CraftResourceTerminalSnapshot(
        CraftResourceTerminalKey key,
        boolean finalized,
        CraftResourcePrimaryTerminationCause primaryTerminationCause,
        String detachReason,
        boolean connectionDetachedObserved,
        long cancelInvocationId,
        String taskTerminationKind,
        String terminalDecisionReason,
        boolean naturalTaskFinished,
        boolean thisOrChildTimedOutAtFinalization,
        boolean thisOrChildTimedOutEverObserved,
        long firstTimedOutObservationTick,
        long lastTimedOutObservationTick,
        String classifiedResultStatus,
        String classifiedResultReason,
        String classifiedResultFidelity,
        String evidenceConclusion,
        CraftResourceResultSendStatus resultSendStatus,
        CraftResourceResultDeliveryStatus resultDeliveryStatus,
        boolean terminalSent,
        boolean resultSendInFlight,
        boolean lifecycleCleared,
        CraftResourceLifecycleClearKind lifecycleClearKind,
        boolean queueContextCleared,
        String contextUnbindReason,
        boolean taskFinishObserved,
        boolean classificationObserved,
        boolean sendOutcomeObserved,
        CraftResourceFinalizationMode finalizationMode,
        CraftResourceCoverageStatus coverageStatus,
        long elapsedTicks,
        long elapsedNanos,
        long terminalAdmissionRequestCount,
        boolean terminalEmissionAttempted,
        boolean terminalEmissionAdmitted,
        boolean terminalEmissionCompleted,
        long lateOrDuplicateSignalCount,
        boolean counterSaturated
) {
}
